# Linear Algebra. Home work N6

## Ivan Prodaiko

$\newcommand{\norm}[1]{\lvert\lvert #1 \rvert\rvert}$

In [21]:
import numpy as np
import numpy.linalg as nla
import scipy.linalg as sla

from numpy import inf

def LDU(A):
    L = np.tril(A)
    np.fill_diagonal(L, 0)
    
    D = np.diag(np.diag(A))
    
    U = np.triu(A)
    np.fill_diagonal(U, 0)
    
    return L, D, U

## Problam 1

### a)

$A = \begin{pmatrix}
    2 & -1 & 0 \\
    -1 & 2 & -1 \\
    0 & -1 & 2
\end{pmatrix} \quad b = \begin{pmatrix}
    1 \\
    0 \\
    1
\end{pmatrix}$

$
\left(\begin{array}{rrr|r}
    2 & -1 & 0 & 1\\
    -1 & 2 & -1 & 0\\
    0 & -1 & 2 & 1
  \end{array}\right) 
  \sim 
  \left(\begin{array}{rrr|r}
    2 & -1 & 0 & 1\\
     & \dfrac{3}{2} & -1 & \dfrac{1}{2}\\
    0 & -1 & 2 & 1
  \end{array}\right)
  \sim 
  \left(\begin{array}{rrr|r}
    2 & -1 & 0 & 1\\
     & \dfrac{3}{2} & -1 & \dfrac{1}{2}\\
    0 & 0 & \dfrac{4}{3} & \dfrac{4}{3}
  \end{array}\right)
$


$x_3 = 1\quad x_2 = 1\quad x_1 = 1$

### b) 

$Ax = b$

$(L + D + U)x = b$

$Dx = -(L+U)x + b$

$x_{i+1} = D^{-1}(L + U)x_i + D^{-1}b$

The **Spectral radius** of a square matrix or a bounded linear operator is **the largest absolute value of its eigenvalues**.

[From wikipedia](https://en.wikipedia.org/wiki/Spectral_radius):

The spectral radius is closely related to the behaviour of the convergence of the power sequence of a matrix; namely, the following theorem holds:

**Theorem.** Let $A \in C^{nxn}$ with spectral radius $p(A)$. Then if $p(A) < 1 \iff \lim_{x\to\infty} A^k = 0$. 

On the other hand if  $p(A) > 1 \iff \lim_{x\to\infty} \norm{A^k} = \infty$. The statement holds for any choice of matrix norm on $C^{nxn}$.

Necessary condition for convergence is: $p(B) = max|\lambda(B)| < 1$

Sufficient: $\norm{B} < 1$

### bc)

In [22]:
def jacobi(A, b, n):
    print('A:\n{}'.format(A))
    print('b:\n{}'.format(b))
    
    L, D, U = LDU(A)
    
    print('L:\n{}'.format(L))
    print('D:\n{}'.format(D))
    print('U:\n{}'.format(U))
    
    B1 = -nla.inv(D).dot(L + U)
    b1 = nla.inv(D).dot(b)

    print("Jacobi iteration matrix B:\n{}".format(B1))
    print("Norm of Jacobi iteration matrix B:\n{}".format(nla.norm(B1)))
    print("Jacobi vector:\n{}".format(b1))

    spec = np.max(nla.eigvals(B1))
    print('Spectral radius of matrix D^-1(L + U):\n{}'.format(spec))
    print('Expect convergance: {}'.format(spec < 1))

    x = np.array([[0], [0], [0]])
    
    j = 0 # used in problem 2

    for i in range(n):
        next_x = B1.dot(x) + b1
        if nla.norm(next_x - x) >= 0.001:
            j += 1
            print("Norm:{}".format(nla.norm(next_x - x)))
        x = next_x
    return x, j

In [23]:
approx, _ = jacobi(
    np.array([
        [2, -1, 0], 
        [-1, 2, -1], 
        [0, -1, 2]
    ]), 
    np.array([
        [1], 
        [0], 
        [1],
    ]),
    2,
)
approx

A:
[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
b:
[[1]
 [0]
 [1]]
L:
[[ 0  0  0]
 [-1  0  0]
 [ 0 -1  0]]
D:
[[2 0 0]
 [0 2 0]
 [0 0 2]]
U:
[[ 0 -1  0]
 [ 0  0 -1]
 [ 0  0  0]]
Jacobi iteration matrix B:
[[-0.   0.5 -0. ]
 [ 0.5 -0.   0.5]
 [-0.   0.5 -0. ]]
Norm of Jacobi iteration matrix B:
1.0
Jacobi vector:
[[0.5]
 [0. ]
 [0.5]]
Spectral radius of matrix D^-1(L + U):
0.7071067811865475
Expect convergance: True
Norm:0.7071067811865476
Norm:0.5


array([[0.5],
       [0.5],
       [0.5]])

### bd)

In [24]:
def gauss_seidel(A, b, n):
    print('A:\n{}'.format(A))
    print('b:\n{}'.format(b))
    
    L, D, U = LDU(A)
    
    print('L:\n{}'.format(L))
    print('D:\n{}'.format(D))
    print('U:\n{}'.format(U))
    
    Bgs = -nla.inv(D + L).dot(U)
    bgs = nla.inv(D + L).dot(b)

    print("Gauss-Seidel iteration matrix B:\n{}".format(Bgs))
    print("Norm of Gauss-Seidel iteration matrix B:\n{}".format(nla.norm(Bgs)))
    print("Gauss-Seidel vector:\n{}".format(bgs))

    spec = np.max(nla.eigvals(Bgs))
    print('Spectral radius of matrix (D + L)^-1(U):\n{}'.format(spec))
    print('Expect convergance: {}'.format(spec < 1))

    x = np.array([[0], [0], [0]])
    
    j = 0

    for i in range(n):
        next_x = Bgs.dot(x) + bgs
        if nla.norm(next_x - x) >= 0.001:
            j += 1
            print("Norm:{}".format(nla.norm(next_x - x)))
        x = next_x
    return x, j

In [25]:
approx, _ = gauss_seidel(
    np.array([
        [2, -1, 0], 
        [-1, 2, -1], 
        [0, -1, 2],
    ]), 
    np.array([
        [1], 
        [0], 
        [1],
    ]),
    2
)
approx

A:
[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
b:
[[1]
 [0]
 [1]]
L:
[[ 0  0  0]
 [-1  0  0]
 [ 0 -1  0]]
D:
[[2 0 0]
 [0 2 0]
 [0 0 2]]
U:
[[ 0 -1  0]
 [ 0  0 -1]
 [ 0  0  0]]
Gauss-Seidel iteration matrix B:
[[-0.     0.5   -0.   ]
 [-0.     0.25   0.5  ]
 [-0.     0.125  0.25 ]]
Norm of Gauss-Seidel iteration matrix B:
0.8003905296791061
Gauss-Seidel vector:
[[0.5  ]
 [0.25 ]
 [0.625]]
Spectral radius of matrix (D + L)^-1(U):
0.5
Expect convergance: True
Norm:0.8385254915624212
Norm:0.4375


array([[0.625 ],
       [0.625 ],
       [0.8125]])

### e) 

In [26]:
def sor(A, b, w, n):
    print('A:\n{}'.format(A))
    print('b:\n{}'.format(b))

    L, D, U = LDU(A)
    
    print('L:\n{}'.format(L))
    print('D:\n{}'.format(D))
    print('U:\n{}'.format(U))
    
    Bsor = -nla.inv(D + w*L).dot((1-w)*D - w*U)
    bsor = w*nla.inv(D + w*L).dot(b)

    print("Successive overrelaxation method itervative matrix B:\n{}".format(Bsor))
    print("Norm of Successive overrelaxation method itverative matrix B:\n{}".format(nla.norm(Bsor)))
    print("Successive overrelaxation method vector:\n{}".format(bsor))

    spec = np.max(nla.eigvals(Bsor))
    print('Spectral radius of matrix (D + L)^-1(U):\n{}'.format(spec))
    print('Expect convergance: {}'.format(spec >= abs(1 - w)))

    x = np.array([[0], [0], [0]])
    
    j = 0

    for i in range(n):
        next_x = Bsor.dot(x) + bsor
        if nla.norm(next_x - x) >= 0.001:
            j += 1
            print("Norm:{}".format(nla.norm(next_x - x)))
        x = next_x
    return x, j

In [27]:
w = 0.1
approx, _ = sor(
    np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]]), 
    np.array([[1], [0], [1]]), 
    w,
    2
)
print("Approximation:\n{} with param w = {}\n\n".format(approx, w))

w = 1.1
approx, _ = sor(
    np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]]), 
    np.array([[1], [0], [1]]), 
    w,
    2
)
print("Approximation:\n{} with param w = {}\n\n".format(approx, w))

A:
[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
b:
[[1]
 [0]
 [1]]
L:
[[ 0  0  0]
 [-1  0  0]
 [ 0 -1  0]]
D:
[[2 0 0]
 [0 2 0]
 [0 0 2]]
U:
[[ 0 -1  0]
 [ 0  0 -1]
 [ 0  0  0]]
Successive overrelaxation method itervative matrix B:
[[-0.9      -0.05     -0.      ]
 [-0.045    -0.9025   -0.05    ]
 [-0.00225  -0.045125 -0.9025  ]]
Norm of Successive overrelaxation method itverative matrix B:
1.5646337680508497
Successive overrelaxation method vector:
[[0.05    ]
 [0.0025  ]
 [0.050125]]
Spectral radius of matrix (D + L)^-1(U):
-0.8353713920895122
Expect convergance: False
Norm:0.07084324685529314
Norm:0.06443862596312576
Approximation:
[[ 0.004875  ]
 [-0.0045125 ]
 [ 0.00466188]] with param w = 0.1


A:
[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
b:
[[1]
 [0]
 [1]]
L:
[[ 0  0  0]
 [-1  0  0]
 [ 0 -1  0]]
D:
[[2 0 0]
 [0 2 0]
 [0 0 2]]
U:
[[ 0 -1  0]
 [ 0  0 -1]
 [ 0  0  0]]
Successive overrelaxation method itervative matrix B:
[[ 0.1      -0.55     -0.      ]
 [ 0.055    -0.2025   -0.55    ]
 [ 0.030

## Problem 2

### a)

The standard convergence condition (for any iterative method) is when the spectral radius of the iteration matrix is less than 1:

$max(\lambda(B)) < 1$

**Gauss-Seidel method** converges for positive definite symmetric matrixes. So, $min(\lambda(A)) > 0$.
Thus, parameter $a$ for Gauss-Seidel method has to be greater than zero.

In [28]:
u = np.array([[1, -1, 1]]).T
a = 1
A = a * np.identity(3) + u.dot(u.T)
b = u

L, D, U = LDU(A)

Bjac = -nla.inv(D).dot(L + U)
print("Jacobi iteration matrix spectral radius: {}\n".format(np.max(nla.eigvals(Bjac))))
Bgs = -nla.inv(D + L).dot(U)
print("Gauss-Seidel iteration matrix spectral radius: {}\n".format(np.max(nla.eigvals(Bgs))))
w = 0.1
Bsor = -nla.inv(D + w*L).dot((1-w)*D - w*U)
print("Successive overrelaxation method iteration matrix spectral radius: {}\n".format(np.max(nla.eigvals(Bsor))))
w = 1.1
Bsor = -nla.inv(D + w*L).dot((1-w)*D - w*U)
print("Successive overrelaxation method iteration matrix spectral radius: {}\n".format(np.max(nla.eigvals(Bsor))))

Jacobi iteration matrix spectral radius: 0.5000000000000001

Gauss-Seidel iteration matrix spectral radius: (0.3125+0.1653594569415369j)

Successive overrelaxation method iteration matrix spectral radius: (-0.8099473809975465+0j)

Successive overrelaxation method iteration matrix spectral radius: (0.009113426318958014+0j)



## b)

In [29]:
a = 0.01
print("\n\nparam a = {}\n\n".format(a))
jacobi(
    a * np.identity(3) + u.dot(u.T),
    np.array([
        [1], 
        [-1], 
        [1],
    ]),
    100,
)

a = 1
print("\n\nparam a = {}\n\n".format(a))
jacobi(
    a * np.identity(3) + u.dot(u.T),
    np.array([
        [1], 
        [-1], 
        [1],
    ]),
    100,
)

a = 100
print("\n\nparam a = {}\n\n".format(a))
jacobi(
    a * np.identity(3) + u.dot(u.T),
    np.array([
        [1], 
        [-1], 
        [1],
    ]),
    100,
)



param a = 0.01


A:
[[ 1.01 -1.    1.  ]
 [-1.    1.01 -1.  ]
 [ 1.   -1.    1.01]]
b:
[[ 1]
 [-1]
 [ 1]]
L:
[[ 0.  0.  0.]
 [-1.  0.  0.]
 [ 1. -1.  0.]]
D:
[[1.01 0.   0.  ]
 [0.   1.01 0.  ]
 [0.   0.   1.01]]
U:
[[ 0. -1.  1.]
 [ 0.  0. -1.]
 [ 0.  0.  0.]]
Jacobi iteration matrix B:
[[-0.          0.99009901 -0.99009901]
 [ 0.99009901 -0.          0.99009901]
 [-0.99009901  0.99009901 -0.        ]]
Norm of Jacobi iteration matrix B:
2.425237369092255
Jacobi vector:
[[ 0.99009901]
 [-0.99009901]
 [ 0.99009901]]
Spectral radius of matrix D^-1(L + U):
0.9900990099009901
Expect convergance: True
Norm:1.7149017896721557
Norm:3.395845128063675
Norm:6.724445798145891
Norm:13.31573425375424
Norm:26.367790601493546
Norm:52.21344673563078
Norm:103.39296383293224
Norm:204.73854224343017
Norm:405.4228559275845
Norm:802.8175364902663
Norm:1589.7376960203296
Norm:3147.9954376640185
Norm:6233.654332007958
Norm:12343.869964372192
Norm:24443.306860142955
Norm:48402.58784186724
Norm:95846.7085977

(array([[ 0.00970874],
        [-0.00970874],
        [ 0.00970874]]), 1)

## c)

In [30]:
a = 0.01
print("\n\nparam a = {}\n\n".format(a))
approx, i = gauss_seidel(
    a * np.identity(3) + u.dot(u.T),
    np.array([
        [1], 
        [-1], 
        [1],
    ]),
    100,
)
print("\nApproximate solution is: {}. Number of iterations done: {}\n".format(approx, i))

a = 1
print("\n\nparam a = {}\n\n".format(a))
approx, i = gauss_seidel(
    a * np.identity(3) + u.dot(u.T),
    np.array([
        [1], 
        [-1], 
        [1],
    ]),
    100,
)
print("\nApproximate solution is: {}. Number of iterations done: {}\n".format(approx, i))

a = 100
print("\n\nparam a = {}\n\n".format(a))
approx, i = gauss_seidel(
    a * np.identity(3) + u.dot(u.T),
    np.array([
        [1], 
        [-1], 
        [1],
    ]),
    100,
)
print("\nApproximate solution is: {}. Number of iterations done: {}\n".format(approx, i))



param a = 0.01


A:
[[ 1.01 -1.    1.  ]
 [-1.    1.01 -1.  ]
 [ 1.   -1.    1.01]]
b:
[[ 1]
 [-1]
 [ 1]]
L:
[[ 0.  0.  0.]
 [-1.  0.  0.]
 [ 1. -1.  0.]]
D:
[[1.01 0.   0.  ]
 [0.   1.01 0.  ]
 [0.   0.   1.01]]
U:
[[ 0. -1.  1.]
 [ 0.  0. -1.]
 [ 0.  0.  0.]]
Gauss-Seidel iteration matrix B:
[[-0.          0.99009901 -0.99009901]
 [-0.          0.98029605  0.00980296]
 [-0.         -0.0097059   0.99000195]]
Norm of Gauss-Seidel iteration matrix B:
1.9753143062847258
Gauss-Seidel vector:
[[ 9.90099010e-01]
 [-9.80296049e-03]
 [ 9.70590148e-05]]
Spectral radius of matrix (D + L)^-1(U):
(0.9851490001465593+0.008461408740825667j)
Expect convergance: True
Norm:0.9901475429762079
Norm:0.013727556290877864
Norm:0.013524836364385562
Norm:0.013325103045485636
Norm:0.013128312255658386
Norm:0.012934420572872137
Norm:0.012743385221666242
Norm:0.012555164063386802
Norm:0.012369715586568977
Norm:0.01218699889746664
Norm:0.012006973710726412
Norm:0.01182960034020355
Norm:0.01165483968991718
Norm

## d)

In [31]:
a = 0.01
print("\n\nparam a = {}\n\n".format(a))
approx, i = sor(
    a * np.identity(3) + u.dot(u.T),
    np.array([
        [1], 
        [-1], 
        [1],
    ]),
    1,
    100,
)
print("\nApproximate solution is: {}. Number of iterations done: {}\n".format(approx, i))

a = 1
print("\n\nparam a = {}\n\n".format(a))
approx, i = sor(
    a * np.identity(3) + u.dot(u.T),
    np.array([
        [1], 
        [-1], 
        [1],
    ]),
    1,
    100,
)
print("\nApproximate solution is: {}. Number of iterations done: {}\n".format(approx, i))

a = 100
print("\n\nparam a = {}\n\n".format(a))
approx, i = sor(
    a * np.identity(3) + u.dot(u.T),
    np.array([
        [1], 
        [-1], 
        [1],
    ]),
    1,
    100,
)
print("\nApproximate solution is: {}. Number of iterations done: {}\n".format(approx, i))



param a = 0.01


A:
[[ 1.01 -1.    1.  ]
 [-1.    1.01 -1.  ]
 [ 1.   -1.    1.01]]
b:
[[ 1]
 [-1]
 [ 1]]
L:
[[ 0.  0.  0.]
 [-1.  0.  0.]
 [ 1. -1.  0.]]
D:
[[1.01 0.   0.  ]
 [0.   1.01 0.  ]
 [0.   0.   1.01]]
U:
[[ 0. -1.  1.]
 [ 0.  0. -1.]
 [ 0.  0.  0.]]
Successive overrelaxation method itervative matrix B:
[[-0.         -0.99009901  0.99009901]
 [-0.         -0.98029605 -0.00980296]
 [-0.          0.0097059  -0.99000195]]
Norm of Successive overrelaxation method itverative matrix B:
1.9753143062847258
Successive overrelaxation method vector:
[[ 9.90099010e-01]
 [-9.80296049e-03]
 [ 9.70590148e-05]]
Spectral radius of matrix (D + L)^-1(U):
(-0+0j)
Expect convergance: True
Norm:0.9901475429762079
Norm:0.013727556290877862
Norm:0.013524836364385562
Norm:0.013325103045485715
Norm:0.013128312255658468
Norm:0.012934420572872054
Norm:0.012743385221666233
Norm:0.012555164063386803
Norm:0.012369715586568903
Norm:0.012186998897466553
Norm:0.012006973710726407
Norm:0.011829600340203545


## Problam 3

**Step 1**: Choose $x_0$ and $\epsilon$. Set $p_0 = r_0 = b - Ax_0$

**Step 2**: For $i = 0, 1, 2, 3...$ do

$
w = Ap_i\\
a_i = \dfrac{\norm{r_i}^2_2}{p_i^Tw}\\
x_{i+1} = x_i + a_ip_i\\
r_{i+1} = r_i - a_iw\\
$

Test for convergence: If $\norm{r_{i+1}}_2^2 \geq \epsilon$, continue.

$
\beta_i = \dfrac{\norm{r_{i+1}}_2^2}{\norm{r_{i}}_2^2} \\
p_{i+1} = r_{i+1} + \beta_ip_i
$


In [32]:
def cg(A, b, n):
    print('A:\n{}'.format(A))
    print('b:\n{}'.format(b))
    
    x = np.array([[0], [0], [0]])
    
    p = b - A.dot(x)
    r = np.copy(p)
    
    for i in range(n):
        w = A.dot(p)
        a = nla.norm(r)/p.T.dot(w)
        x = x + a*p
        r = r - a*w
        B = 9*10**(-8)
        p = r + B*p
    return x

### a)

In [33]:
cg(
    np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]]), 
    np.array([[1], [0], [1]]),
    100
)

A:
[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
b:
[[1]
 [0]
 [1]]


array([[1.00128286],
       [0.97380662],
       [1.00128286]])

### b)

In [34]:
u = np.array([[1, -1, 1]]).T
a = 1

cg(
    a * np.identity(3) + u.dot(u.T), 
    u,
    100
)

A:
[[ 2. -1.  1.]
 [-1.  2. -1.]
 [ 1. -1.  2.]]
b:
[[ 1]
 [-1]
 [ 1]]


array([[ 0.2886736],
       [-0.2886736],
       [ 0.2886736]])

## Problam 4

In [35]:
def eigenvalue(A, v):
    Av = A.dot(v)
    return v.dot(Av)

def power_iteration(A):
    """ function is taken from http://mlwiki.org/index.php/Power_Iteration """
    n, d = A.shape

    v = np.ones(d) / np.sqrt(d)
    ev = eigenvalue(A, v)

    while True:
        Av = A.dot(v)
        v_new = Av / np.linalg.norm(Av)

        ev_new = eigenvalue(A, v_new)
        if np.abs(ev - ev_new) < 0.01:
            break

        v = v_new
        ev = ev_new

    return ev_new, v_new

### a)

In [36]:
np.random.seed(512)

D = np.diag(np.arange(1, 11))
P = np.random.rand(10, 10)
P_inv = nla.inv(P)

A = P.dot(D).dot(P_inv)
print("Matrix A:\n{}".format(np.around(A, decimals = 2)))

print("Eigenvalues of A are: \n{}".format(nla.eigvals(A)))

eigenval, eigenvec = power_iteration(A)
print("The biggest eigenvalue approximation with power method:\n{}".format(eigenval))
print("Corresponding eigenvector is:\n{}".format(eigenvec))

Matrix A:
[[ 7.04 -1.28 -0.81 -0.07  2.35 -0.32 -0.55 -2.24  1.89  0.33]
 [ 0.66  8.22 12.19  0.37 -3.45 -6.4   0.61 -0.73  0.7  -5.68]
 [ 2.49  1.36  7.09 -1.22  0.35 -1.43  0.2  -0.34  0.91 -3.04]
 [ 1.89  1.8   3.74  1.68 -0.28 -2.84 -1.42  1.   -0.65 -1.13]
 [ 1.56  1.16  5.58 -0.77  4.89 -4.49 -1.95 -1.78  2.98 -0.64]
 [ 4.8   1.25  0.12 -3.44  1.77  5.83  1.48  1.77 -2.94 -5.63]
 [ 1.53 -0.37  1.28 -0.34  0.45 -1.69  5.58 -2.9   2.4  -0.26]
 [ 3.96  2.51  5.69 -5.88 -0.44 -3.57  0.5   9.8  -2.42 -6.33]
 [ 2.1  -3.41 -1.58 -1.02  6.12 -2.75 -4.33 -2.54  5.9   5.57]
 [ 2.09  1.59  5.38 -0.85 -1.35 -2.43  2.54 -0.59  1.03 -1.03]]
Eigenvalues of A are: 
[10.  9.  1.  8.  7.  6.  5.  2.  4.  3.]
The biggest eigenvalue approximation with power method:
9.930085271625204
Corresponding eigenvector is:
[0.39766637 0.24734735 0.2859386  0.08084125 0.45856598 0.09716147
 0.41782628 0.02312014 0.45208271 0.3052365 ]


### b) 

[Inverse iteration](http://ranger.uta.edu/~huber/cse4345/Notes/Eigenvalues.pdf) corresponds to power iteration with the inverse matrix $A^{-1}$.

Inverse iteration and power iteration can only find the smallest and the largest eigenvalues 

In [37]:
A_inv = nla.inv(A)

eigenval, eigenvec = power_iteration(A_inv)
print("The smallest eigenvalue approximation with power method:\n{}".format(eigenval))
print("Corresponding eigenvector is:\n{}".format(eigenvec))

The smallest eigenvalue approximation with power method:
1.0174879310504454
Corresponding eigenvector is:
[0.05819011 0.32402077 0.06663947 0.42387673 0.18040681 0.3311812
 0.16909663 0.49304096 0.52589938 0.13050413]


## Problam 5

In [38]:
def qr_iteration(A):
    for i in range(100):
        Q, R = sla.qr(A)
        A = np.dot(R, Q)
    return np.diag(A)

### a)

In [39]:
np.random.seed(512)

u = np.random.rand(10, 1)

A = D + u.dot(u.T)
np.around(A, decimals = 2)

print("Eigenvalues of A are: \n{}".format(nla.eigvals(A)))

eigvals = qr_iteration(A)
print("Eigenvalues approximation with QR method are: \n{}".format(eigvals))

print("despite sort order different eigenvalues are the same")

Eigenvalues of A are: 
[10.84161204  1.00854716  2.03152472  9.0593145   8.27073703  3.11012194
  7.15376454  4.11301172  6.0741731   5.00580825]
Eigenvalues approximation with QR method are: 
[10.84161204  9.05931436  8.27073716  7.15376454  6.0741731   5.00580825
  4.11301172  3.11012194  2.03152472  1.00854716]
despite sort order different eigenvalues are the same


### b)

In [40]:
power_iteration(A)
print("The biggest eigenvalue approximation with power method:\n{}".format(eigenval))
print("Corresponding eigenvector is:\n{}".format(eigenvec))

The biggest eigenvalue approximation with power method:
1.0174879310504454
Corresponding eigenvector is:
[0.05819011 0.32402077 0.06663947 0.42387673 0.18040681 0.3311812
 0.16909663 0.49304096 0.52589938 0.13050413]
